services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DMK\Mk30xLegacy\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    DMK\Mk30xLegacy\Domain\Manager\ConfigurationManager:
        public: true

    DMK\Mk30xLegacy\Middleware\LegacyRedirect:
        public: true
