services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DMK\Mk30xLegacy\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    DMK\Mk30xLegacy\Domain\Manager\ConfigurationManager:
        public: true

    DMK\Mk30xLegacy\Middleware\RedirectMiddleware:
        public: true

    DMK\Mk30xLegacy\System\Routing\Matcher\LegacyUriMatcher:
        tags:
            -
                name: 'mk30xlegacy.routing.matcher'
                priority: 200
